/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module lfsr_axi_top(clk, resetslave, s_axi_awaddr, s_axi_awvalid, s_axi_awready, s_axi_wdata, s_axi_wvalid, s_axi_wready, s_axi_bresp, s_axi_bvalid, s_axi_bready, s_axi_araddr, s_axi_arvalid, s_axi_arready, s_axi_rdata, s_axi_rvalid, s_axi_rready);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire [3:0] _150_;
  wire [1:0] _151_;
  wire [1:0] _152_;
  wire [1:0] _153_;
  wire [1:0] _154_;
  wire [1:0] _155_;
  wire [1:0] _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire [1:0] _162_;
  wire [1:0] _163_;
  wire [1:0] _164_;
  wire [1:0] _165_;
  wire [1:0] _166_;
  wire [1:0] _167_;
  wire [1:0] _168_;
  wire [1:0] _169_;
  wire [1:0] _170_;
  wire [3:0] _171_;
  wire [1:0] _172_;
  wire _173_;
  wire [1:0] _174_;
  wire _175_;
  wire _176_;
  wire [1:0] _177_;
  wire _178_;
  wire [1:0] _179_;
  wire [1:0] _180_;
  wire [1:0] _181_;
  wire [3:0] _182_;
  wire [3:0] _183_;
  wire [1:0] _184_;
  wire [3:0] _185_;
  wire [3:0] _186_;
  wire [3:0] _187_;
  wire [1:0] _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire [7:0] _197_;
  wire _198_;
  wire [1:0] _199_;
  wire [1:0] _200_;
  wire [1:0] _201_;
  wire _202_;
  wire _203_;
  wire [1:0] _204_;
  wire [1:0] _205_;
  wire _206_;
  wire _207_;
  wire [31:0] _208_;
  wire [3:0] _209_;
  wire [7:0] _210_;
  wire [7:0] _211_;
  wire _212_;
  wire [7:0] _213_;
  wire [7:0] _214_;
  wire [7:0] _215_;
  wire [5:0] _216_;
  wire [5:0] _217_;
  wire [2:0] _218_;
  wire [1:0] _219_;
  wire [1:0] _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire [2:0] _224_;
  wire [2:0] _225_;
  wire _226_;
  wire _227_;
  wire [1:0] _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  input clk;
  wire clk;
  wire [7:0] ctrl_reg;
  wire enable;
  wire [7:0] lfsr_out;
  wire load;
  input resetslave;
  wire resetslave;
  input [3:0] s_axi_araddr;
  wire [3:0] s_axi_araddr;
  output s_axi_arready;
  wire s_axi_arready;
  input s_axi_arvalid;
  wire s_axi_arvalid;
  input [3:0] s_axi_awaddr;
  wire [3:0] s_axi_awaddr;
  output s_axi_awready;
  wire s_axi_awready;
  input s_axi_awvalid;
  wire s_axi_awvalid;
  input s_axi_bready;
  wire s_axi_bready;
  output [1:0] s_axi_bresp;
  wire [1:0] s_axi_bresp;
  output s_axi_bvalid;
  wire s_axi_bvalid;
  output [7:0] s_axi_rdata;
  wire [7:0] s_axi_rdata;
  input s_axi_rready;
  wire s_axi_rready;
  output s_axi_rvalid;
  wire s_axi_rvalid;
  input [7:0] s_axi_wdata;
  wire [7:0] s_axi_wdata;
  output s_axi_wready;
  wire s_axi_wready;
  input s_axi_wvalid;
  wire s_axi_wvalid;
  wire [7:0] seed_reg;
  wire [7:0] taps_reg;
  wire \u_axi_slave.clk ;
  wire [7:0] \u_axi_slave.ctrl_reg ;
  wire [7:0] \u_axi_slave.lfsr_data ;
  wire \u_axi_slave.read_state ;
  wire \u_axi_slave.resetn ;
  wire [3:0] \u_axi_slave.s_axi_araddr ;
  wire \u_axi_slave.s_axi_arready ;
  wire \u_axi_slave.s_axi_arvalid ;
  wire [3:0] \u_axi_slave.s_axi_awaddr ;
  wire \u_axi_slave.s_axi_awready ;
  wire \u_axi_slave.s_axi_awvalid ;
  wire \u_axi_slave.s_axi_bready ;
  wire [1:0] \u_axi_slave.s_axi_bresp ;
  wire \u_axi_slave.s_axi_bvalid ;
  wire [7:0] \u_axi_slave.s_axi_rdata ;
  wire \u_axi_slave.s_axi_rready ;
  wire \u_axi_slave.s_axi_rvalid ;
  wire [7:0] \u_axi_slave.s_axi_wdata ;
  wire \u_axi_slave.s_axi_wready ;
  wire \u_axi_slave.s_axi_wvalid ;
  wire [7:0] \u_axi_slave.seed_reg ;
  wire [7:0] \u_axi_slave.taps_reg ;
  wire [3:0] \u_axi_slave.write_addr ;
  wire [1:0] \u_axi_slave.write_state ;
  wire \u_lfsr.clk ;
  wire \u_lfsr.enable ;
  wire \u_lfsr.feedback ;
  wire [7:0] \u_lfsr.lfsr_out ;
  wire \u_lfsr.lfsr_stuck_zero ;
  wire \u_lfsr.load ;
  wire [7:0] \u_lfsr.seed ;
  wire [7:0] \u_lfsr.taps ;
  sky130_fd_sc_hd__clkinv_1 _234_ (
    .A(_091_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _235_ (
    .A(_093_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _236_ (
    .A(_096_),
    .SLEEP(_097_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2b_1 _237_ (
    .A_N(_126_),
    .B(_125_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _238_ (
    .A(_055_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _239_ (
    .A(_125_),
    .B(_126_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__o21ai_0 _240_ (
    .A1(_125_),
    .A2(_054_),
    .B1(_126_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(_121_),
    .B(_122_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__or3_1 _242_ (
    .A(_121_),
    .B(_122_),
    .C(_123_),
    .X(_057_)
  );
  sky130_fd_sc_hd__nor3_1 _243_ (
    .A(_124_),
    .B(_055_),
    .C(_057_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _244_ (
    .A(_123_),
    .B(_056_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor3_1 _245_ (
    .A(_124_),
    .B(_055_),
    .C(_058_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(_124_),
    .B(_080_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _247_ (
    .A(_057_),
    .B(_059_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(_092_),
    .B(_095_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor3b_1 _249_ (
    .A(_125_),
    .B(_093_),
    .C_N(_126_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21oi_1 _250_ (
    .A1(_081_),
    .A2(_060_),
    .B1(_009_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor3_1 _251_ (
    .A(_125_),
    .B(_126_),
    .C(_060_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _252_ (
    .A(_071_),
    .B(_104_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2b_1 _253_ (
    .A_N(_094_),
    .B(_104_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(_127_),
    .B(_113_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(_128_),
    .B(_114_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xor2_1 _256_ (
    .A(_010_),
    .B(_011_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(_129_),
    .B(_115_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(_130_),
    .B(_116_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _259_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__xnor2_1 _260_ (
    .A(_012_),
    .B(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(_131_),
    .B(_117_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _262_ (
    .A(_132_),
    .B(_118_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__xnor2_1 _263_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _264_ (
    .A(_133_),
    .B(_119_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(_134_),
    .B(_120_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xnor2_1 _266_ (
    .A(_020_),
    .B(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _267_ (
    .A(_019_),
    .B(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__or4_1 _268_ (
    .A(_131_),
    .B(_132_),
    .C(_133_),
    .D(_134_),
    .X(_024_)
  );
  sky130_fd_sc_hd__or4_1 _269_ (
    .A(_127_),
    .B(_128_),
    .C(_129_),
    .D(_130_),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _270_ (
    .A(_024_),
    .B(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a21oi_1 _271_ (
    .A1(_016_),
    .A2(_023_),
    .B1(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21ai_0 _272_ (
    .A1(_016_),
    .A2(_023_),
    .B1(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _273_ (
    .A(_096_),
    .SLEEP(_097_),
    .X(_029_)
  );
  sky130_fd_sc_hd__a22o_1 _274_ (
    .A1(_097_),
    .A2(_105_),
    .B1(_028_),
    .B2(_029_),
    .X(_072_)
  );
  sky130_fd_sc_hd__a22o_1 _275_ (
    .A1(_097_),
    .A2(_106_),
    .B1(_029_),
    .B2(_127_),
    .X(_073_)
  );
  sky130_fd_sc_hd__a22o_1 _276_ (
    .A1(_097_),
    .A2(_107_),
    .B1(_029_),
    .B2(_128_),
    .X(_074_)
  );
  sky130_fd_sc_hd__o21ai_0 _277_ (
    .A1(_129_),
    .A2(_026_),
    .B1(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _278_ (
    .A(_097_),
    .B(_108_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(_030_),
    .B(_031_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__o21ai_0 _280_ (
    .A1(_130_),
    .A2(_026_),
    .B1(_029_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(_097_),
    .B(_109_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _282_ (
    .A(_032_),
    .B(_033_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a22o_1 _283_ (
    .A1(_097_),
    .A2(_110_),
    .B1(_029_),
    .B2(_131_),
    .X(_077_)
  );
  sky130_fd_sc_hd__a22o_1 _284_ (
    .A1(_097_),
    .A2(_111_),
    .B1(_029_),
    .B2(_132_),
    .X(_078_)
  );
  sky130_fd_sc_hd__a22o_1 _285_ (
    .A1(_097_),
    .A2(_112_),
    .B1(_029_),
    .B2(_133_),
    .X(_079_)
  );
  sky130_fd_sc_hd__a211o_1 _286_ (
    .A1(_123_),
    .A2(_124_),
    .B1(_121_),
    .C1(_122_),
    .X(_086_)
  );
  sky130_fd_sc_hd__o21ai_0 _287_ (
    .A1(_071_),
    .A2(_104_),
    .B1(_001_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor4bb_1 _288_ (
    .A(_087_),
    .B(_088_),
    .C_N(_089_),
    .D_N(_090_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor4b_1 _289_ (
    .A(_087_),
    .B(_088_),
    .C(_089_),
    .D_N(_090_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor4_1 _290_ (
    .A(_087_),
    .B(_088_),
    .C(_089_),
    .D(_090_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _291_ (
    .A(_096_),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor4b_1 _292_ (
    .A(_087_),
    .B(_088_),
    .C(_090_),
    .D_N(_089_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a222oi_1 _293_ (
    .A1(_127_),
    .A2(_034_),
    .B1(_035_),
    .B2(_113_),
    .C1(_038_),
    .C2(_105_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(_037_),
    .B(_039_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(_097_),
    .B(_036_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a222oi_1 _296_ (
    .A1(_128_),
    .A2(_034_),
    .B1(_035_),
    .B2(_114_),
    .C1(_038_),
    .C2(_106_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _297_ (
    .A(_040_),
    .B(_041_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(_098_),
    .B(_036_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a222oi_1 _299_ (
    .A1(_129_),
    .A2(_034_),
    .B1(_035_),
    .B2(_115_),
    .C1(_038_),
    .C2(_107_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _300_ (
    .A(_042_),
    .B(_043_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(_099_),
    .B(_036_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__a222oi_1 _302_ (
    .A1(_130_),
    .A2(_034_),
    .B1(_035_),
    .B2(_116_),
    .C1(_038_),
    .C2(_108_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _303_ (
    .A(_044_),
    .B(_045_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _304_ (
    .A(_100_),
    .B(_036_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a222oi_1 _305_ (
    .A1(_131_),
    .A2(_034_),
    .B1(_035_),
    .B2(_117_),
    .C1(_038_),
    .C2(_109_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _306_ (
    .A(_046_),
    .B(_047_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(_101_),
    .B(_036_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a222oi_1 _308_ (
    .A1(_132_),
    .A2(_034_),
    .B1(_035_),
    .B2(_118_),
    .C1(_038_),
    .C2(_110_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _309_ (
    .A(_048_),
    .B(_049_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _310_ (
    .A(_102_),
    .B(_036_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a222oi_1 _311_ (
    .A1(_133_),
    .A2(_034_),
    .B1(_035_),
    .B2(_119_),
    .C1(_038_),
    .C2(_111_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _312_ (
    .A(_050_),
    .B(_051_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _313_ (
    .A(_103_),
    .B(_036_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a222oi_1 _314_ (
    .A1(_134_),
    .A2(_034_),
    .B1(_035_),
    .B2(_120_),
    .C1(_038_),
    .C2(_112_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _315_ (
    .A(_052_),
    .B(_053_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _316_ (
    .A(_125_),
    .B(_126_),
    .C(_060_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _317_ (
    .A(_055_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__clkinv_1 _318_ (
    .A(_055_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _319_ (
    .A(_071_),
    .B(_104_),
    .Y(_062_)
  );
  \$_SDFF_PN0_  \u_axi_slave.read_state_reg  /* _320_ */ (
    .C(clk),
    .D(_202_),
    .Q(\u_axi_slave.read_state ),
    .R(resetslave)
  );
  \$_SDFFE_PN1P_  \u_lfsr.lfsr_out_reg[0]  /* _321_ */ (
    .C(clk),
    .D(_215_[0]),
    .E(_135_),
    .Q(\u_lfsr.lfsr_out [0]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_lfsr.lfsr_out_reg[1]  /* _322_ */ (
    .C(clk),
    .D(_215_[1]),
    .E(_135_),
    .Q(\u_lfsr.lfsr_out [1]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_lfsr.lfsr_out_reg[2]  /* _323_ */ (
    .C(clk),
    .D(_215_[2]),
    .E(_135_),
    .Q(\u_lfsr.lfsr_out [2]),
    .R(resetslave)
  );
  \$_SDFFE_PN1P_  \u_lfsr.lfsr_out_reg[3]  /* _324_ */ (
    .C(clk),
    .D(_215_[3]),
    .E(_135_),
    .Q(\u_lfsr.lfsr_out [3]),
    .R(resetslave)
  );
  \$_SDFFE_PN1P_  \u_lfsr.lfsr_out_reg[4]  /* _325_ */ (
    .C(clk),
    .D(_215_[4]),
    .E(_135_),
    .Q(\u_lfsr.lfsr_out [4]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_lfsr.lfsr_out_reg[5]  /* _326_ */ (
    .C(clk),
    .D(_215_[5]),
    .E(_135_),
    .Q(\u_lfsr.lfsr_out [5]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_lfsr.lfsr_out_reg[6]  /* _327_ */ (
    .C(clk),
    .D(_215_[6]),
    .E(_135_),
    .Q(\u_lfsr.lfsr_out [6]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_lfsr.lfsr_out_reg[7]  /* _328_ */ (
    .C(clk),
    .D(_215_[7]),
    .E(_135_),
    .Q(\u_lfsr.lfsr_out [7]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_wready_reg  /* _329_ */ (
    .C(clk),
    .D(_198_),
    .E(_218_[2]),
    .Q(\u_axi_slave.s_axi_wready ),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_bresp_reg[0]  /* _330_ */ (
    .C(clk),
    .D(_228_[0]),
    .E(_218_[1]),
    .Q(\u_axi_slave.s_axi_bresp [0]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_bresp_reg[1]  /* _331_ */ (
    .C(clk),
    .D(_228_[1]),
    .E(_218_[1]),
    .Q(\u_axi_slave.s_axi_bresp [1]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_bvalid_reg  /* _332_ */ (
    .C(clk),
    .D(_226_),
    .E(_140_),
    .Q(\u_axi_slave.s_axi_bvalid ),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.ctrl_reg_reg[0]  /* _333_ */ (
    .C(clk),
    .D(s_axi_wdata[0]),
    .E(_141_),
    .Q(\u_axi_slave.ctrl_reg [0]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.ctrl_reg_reg[1]  /* _334_ */ (
    .C(clk),
    .D(s_axi_wdata[1]),
    .E(_141_),
    .Q(\u_axi_slave.ctrl_reg [1]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.ctrl_reg_reg[2]  /* _335_ */ (
    .C(clk),
    .D(s_axi_wdata[2]),
    .E(_141_),
    .Q(\u_axi_slave.ctrl_reg [2]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.ctrl_reg_reg[3]  /* _336_ */ (
    .C(clk),
    .D(s_axi_wdata[3]),
    .E(_141_),
    .Q(\u_axi_slave.ctrl_reg [3]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.ctrl_reg_reg[4]  /* _337_ */ (
    .C(clk),
    .D(s_axi_wdata[4]),
    .E(_141_),
    .Q(\u_axi_slave.ctrl_reg [4]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.ctrl_reg_reg[5]  /* _338_ */ (
    .C(clk),
    .D(s_axi_wdata[5]),
    .E(_141_),
    .Q(\u_axi_slave.ctrl_reg [5]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.ctrl_reg_reg[6]  /* _339_ */ (
    .C(clk),
    .D(s_axi_wdata[6]),
    .E(_141_),
    .Q(\u_axi_slave.ctrl_reg [6]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.ctrl_reg_reg[7]  /* _340_ */ (
    .C(clk),
    .D(s_axi_wdata[7]),
    .E(_141_),
    .Q(\u_axi_slave.ctrl_reg [7]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.seed_reg_reg[0]  /* _341_ */ (
    .C(clk),
    .D(s_axi_wdata[0]),
    .E(_142_),
    .Q(\u_axi_slave.seed_reg [0]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.seed_reg_reg[1]  /* _342_ */ (
    .C(clk),
    .D(s_axi_wdata[1]),
    .E(_142_),
    .Q(\u_axi_slave.seed_reg [1]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.seed_reg_reg[2]  /* _343_ */ (
    .C(clk),
    .D(s_axi_wdata[2]),
    .E(_142_),
    .Q(\u_axi_slave.seed_reg [2]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.seed_reg_reg[3]  /* _344_ */ (
    .C(clk),
    .D(s_axi_wdata[3]),
    .E(_142_),
    .Q(\u_axi_slave.seed_reg [3]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.seed_reg_reg[4]  /* _345_ */ (
    .C(clk),
    .D(s_axi_wdata[4]),
    .E(_142_),
    .Q(\u_axi_slave.seed_reg [4]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.seed_reg_reg[5]  /* _346_ */ (
    .C(clk),
    .D(s_axi_wdata[5]),
    .E(_142_),
    .Q(\u_axi_slave.seed_reg [5]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.seed_reg_reg[6]  /* _347_ */ (
    .C(clk),
    .D(s_axi_wdata[6]),
    .E(_142_),
    .Q(\u_axi_slave.seed_reg [6]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.seed_reg_reg[7]  /* _348_ */ (
    .C(clk),
    .D(s_axi_wdata[7]),
    .E(_142_),
    .Q(\u_axi_slave.seed_reg [7]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.taps_reg_reg[0]  /* _349_ */ (
    .C(clk),
    .D(s_axi_wdata[0]),
    .E(_143_),
    .Q(\u_axi_slave.taps_reg [0]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.taps_reg_reg[1]  /* _350_ */ (
    .C(clk),
    .D(s_axi_wdata[1]),
    .E(_143_),
    .Q(\u_axi_slave.taps_reg [1]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.taps_reg_reg[2]  /* _351_ */ (
    .C(clk),
    .D(s_axi_wdata[2]),
    .E(_143_),
    .Q(\u_axi_slave.taps_reg [2]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.taps_reg_reg[3]  /* _352_ */ (
    .C(clk),
    .D(s_axi_wdata[3]),
    .E(_143_),
    .Q(\u_axi_slave.taps_reg [3]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.taps_reg_reg[4]  /* _353_ */ (
    .C(clk),
    .D(s_axi_wdata[4]),
    .E(_143_),
    .Q(\u_axi_slave.taps_reg [4]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.taps_reg_reg[5]  /* _354_ */ (
    .C(clk),
    .D(s_axi_wdata[5]),
    .E(_143_),
    .Q(\u_axi_slave.taps_reg [5]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.taps_reg_reg[6]  /* _355_ */ (
    .C(clk),
    .D(s_axi_wdata[6]),
    .E(_143_),
    .Q(\u_axi_slave.taps_reg [6]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.taps_reg_reg[7]  /* _356_ */ (
    .C(clk),
    .D(s_axi_wdata[7]),
    .E(_143_),
    .Q(\u_axi_slave.taps_reg [7]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.write_state_reg[0]  /* _357_ */ (
    .C(clk),
    .D(_219_[0]),
    .E(_144_),
    .Q(\u_axi_slave.write_state [0]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.write_state_reg[1]  /* _358_ */ (
    .C(clk),
    .D(_219_[1]),
    .E(_144_),
    .Q(\u_axi_slave.write_state [1]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.write_addr_reg[0]  /* _359_ */ (
    .C(clk),
    .D(s_axi_awaddr[0]),
    .E(_145_),
    .Q(\u_axi_slave.write_addr [0]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.write_addr_reg[1]  /* _360_ */ (
    .C(clk),
    .D(s_axi_awaddr[1]),
    .E(_145_),
    .Q(\u_axi_slave.write_addr [1]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.write_addr_reg[2]  /* _361_ */ (
    .C(clk),
    .D(s_axi_awaddr[2]),
    .E(_145_),
    .Q(\u_axi_slave.write_addr [2]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.write_addr_reg[3]  /* _362_ */ (
    .C(clk),
    .D(s_axi_awaddr[3]),
    .E(_145_),
    .Q(\u_axi_slave.write_addr [3]),
    .R(resetslave)
  );
  \$_SDFFE_PN0N_  \u_axi_slave.s_axi_arready_reg  /* _363_ */ (
    .C(clk),
    .D(_212_),
    .E(\u_axi_slave.read_state ),
    .Q(\u_axi_slave.s_axi_arready ),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_rdata_reg[0]  /* _364_ */ (
    .C(clk),
    .D(_210_[0]),
    .E(_146_),
    .Q(\u_axi_slave.s_axi_rdata [0]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_rdata_reg[1]  /* _365_ */ (
    .C(clk),
    .D(_210_[1]),
    .E(_146_),
    .Q(\u_axi_slave.s_axi_rdata [1]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_rdata_reg[2]  /* _366_ */ (
    .C(clk),
    .D(_210_[2]),
    .E(_146_),
    .Q(\u_axi_slave.s_axi_rdata [2]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_rdata_reg[3]  /* _367_ */ (
    .C(clk),
    .D(_210_[3]),
    .E(_146_),
    .Q(\u_axi_slave.s_axi_rdata [3]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_rdata_reg[4]  /* _368_ */ (
    .C(clk),
    .D(_210_[4]),
    .E(_146_),
    .Q(\u_axi_slave.s_axi_rdata [4]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_rdata_reg[5]  /* _369_ */ (
    .C(clk),
    .D(_210_[5]),
    .E(_146_),
    .Q(\u_axi_slave.s_axi_rdata [5]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_rdata_reg[6]  /* _370_ */ (
    .C(clk),
    .D(_210_[6]),
    .E(_146_),
    .Q(\u_axi_slave.s_axi_rdata [6]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_rdata_reg[7]  /* _371_ */ (
    .C(clk),
    .D(_210_[7]),
    .E(_146_),
    .Q(\u_axi_slave.s_axi_rdata [7]),
    .R(resetslave)
  );
  \$_SDFFE_PN0P_  \u_axi_slave.s_axi_rvalid_reg  /* _372_ */ (
    .C(clk),
    .D(_206_),
    .E(_139_),
    .Q(\u_axi_slave.s_axi_rvalid ),
    .R(resetslave)
  );
  assign _224_[2:1] = 2'h1;
  assign _204_[1] = _199_[1];
  assign _201_[0] = \u_axi_slave.read_state ;
  assign _216_[3:2] = 2'h2;
  assign ctrl_reg = \u_axi_slave.ctrl_reg ;
  assign enable = \u_axi_slave.ctrl_reg [0];
  assign lfsr_out = \u_lfsr.lfsr_out ;
  assign load = \u_axi_slave.ctrl_reg [1];
  assign s_axi_arready = \u_axi_slave.s_axi_arready ;
  assign s_axi_awready = \u_axi_slave.s_axi_wready ;
  assign s_axi_bresp = \u_axi_slave.s_axi_bresp ;
  assign s_axi_bvalid = \u_axi_slave.s_axi_bvalid ;
  assign s_axi_rdata = \u_axi_slave.s_axi_rdata ;
  assign s_axi_rvalid = \u_axi_slave.s_axi_rvalid ;
  assign s_axi_wready = \u_axi_slave.s_axi_wready ;
  assign seed_reg = \u_axi_slave.seed_reg ;
  assign taps_reg = \u_axi_slave.taps_reg ;
  assign \u_axi_slave.clk  = clk;
  assign \u_axi_slave.lfsr_data  = \u_lfsr.lfsr_out ;
  assign \u_axi_slave.resetn  = resetslave;
  assign \u_axi_slave.s_axi_araddr  = s_axi_araddr;
  assign \u_axi_slave.s_axi_arvalid  = s_axi_arvalid;
  assign \u_axi_slave.s_axi_awaddr  = s_axi_awaddr;
  assign \u_axi_slave.s_axi_awready  = \u_axi_slave.s_axi_wready ;
  assign \u_axi_slave.s_axi_awvalid  = s_axi_awvalid;
  assign \u_axi_slave.s_axi_bready  = s_axi_bready;
  assign \u_axi_slave.s_axi_rready  = s_axi_rready;
  assign \u_axi_slave.s_axi_wdata  = s_axi_wdata;
  assign \u_axi_slave.s_axi_wvalid  = s_axi_wvalid;
  assign \u_lfsr.clk  = clk;
  assign \u_lfsr.enable  = \u_axi_slave.ctrl_reg [0];
  assign \u_lfsr.load  = \u_axi_slave.ctrl_reg [1];
  assign \u_lfsr.seed  = \u_axi_slave.seed_reg ;
  assign \u_lfsr.taps  = \u_axi_slave.taps_reg ;
  assign _085_ = 1'h0;
  assign _096_ = \u_axi_slave.ctrl_reg [0];
  assign _097_ = \u_axi_slave.ctrl_reg [1];
  assign _135_ = _000_;
  assign _218_[1] = _080_;
  assign _218_[2] = _081_;
  assign _140_ = _002_;
  assign _141_ = _003_;
  assign _142_ = _004_;
  assign _143_ = _005_;
  assign _144_ = _006_;
  assign _145_ = _007_;
  assign _091_ = s_axi_arvalid;
  assign _146_ = _008_;
  assign _139_ = _001_;
  assign _104_ = \u_axi_slave.read_state ;
  assign _127_ = \u_lfsr.lfsr_out [0];
  assign _128_ = \u_lfsr.lfsr_out [1];
  assign _129_ = \u_lfsr.lfsr_out [2];
  assign _130_ = \u_lfsr.lfsr_out [3];
  assign _131_ = \u_lfsr.lfsr_out [4];
  assign _132_ = \u_lfsr.lfsr_out [5];
  assign _133_ = \u_lfsr.lfsr_out [6];
  assign _134_ = \u_lfsr.lfsr_out [7];
  assign _121_ = \u_axi_slave.write_addr [0];
  assign _122_ = \u_axi_slave.write_addr [1];
  assign _123_ = \u_axi_slave.write_addr [2];
  assign _124_ = \u_axi_slave.write_addr [3];
  assign _125_ = \u_axi_slave.write_state [0];
  assign _126_ = \u_axi_slave.write_state [1];
  assign _087_ = s_axi_araddr[0];
  assign _088_ = s_axi_araddr[1];
  assign _089_ = s_axi_araddr[2];
  assign _090_ = s_axi_araddr[3];
  assign _092_ = s_axi_awvalid;
  assign _095_ = s_axi_wvalid;
  assign _105_ = \u_axi_slave.seed_reg [0];
  assign _215_[0] = _072_;
  assign _106_ = \u_axi_slave.seed_reg [1];
  assign _215_[1] = _073_;
  assign _107_ = \u_axi_slave.seed_reg [2];
  assign _215_[2] = _074_;
  assign _108_ = \u_axi_slave.seed_reg [3];
  assign _215_[3] = _075_;
  assign _109_ = \u_axi_slave.seed_reg [4];
  assign _215_[4] = _076_;
  assign _110_ = \u_axi_slave.seed_reg [5];
  assign _215_[5] = _077_;
  assign _111_ = \u_axi_slave.seed_reg [6];
  assign _215_[6] = _078_;
  assign _112_ = \u_axi_slave.seed_reg [7];
  assign _215_[7] = _079_;
  assign _093_ = s_axi_bready;
  assign _228_[0] = _085_;
  assign _228_[1] = _086_;
  assign _198_ = _060_;
  assign _094_ = s_axi_rready;
  assign _212_ = _071_;
  assign _219_[0] = _082_;
  assign _219_[1] = _083_;
  assign _226_ = _084_;
  assign _202_ = _061_;
  assign _206_ = _062_;
  assign _210_[0] = _063_;
  assign _210_[1] = _064_;
  assign _210_[2] = _065_;
  assign _210_[3] = _066_;
  assign _210_[4] = _067_;
  assign _210_[5] = _068_;
  assign _210_[6] = _069_;
  assign _210_[7] = _070_;
  assign _113_ = \u_axi_slave.taps_reg [0];
  assign _114_ = \u_axi_slave.taps_reg [1];
  assign _115_ = \u_axi_slave.taps_reg [2];
  assign _116_ = \u_axi_slave.taps_reg [3];
  assign _117_ = \u_axi_slave.taps_reg [4];
  assign _118_ = \u_axi_slave.taps_reg [5];
  assign _119_ = \u_axi_slave.taps_reg [6];
  assign _120_ = \u_axi_slave.taps_reg [7];
  assign _098_ = \u_axi_slave.ctrl_reg [2];
  assign _099_ = \u_axi_slave.ctrl_reg [3];
  assign _100_ = \u_axi_slave.ctrl_reg [4];
  assign _101_ = \u_axi_slave.ctrl_reg [5];
  assign _102_ = \u_axi_slave.ctrl_reg [6];
  assign _103_ = \u_axi_slave.ctrl_reg [7];
endmodule
